package util

const (
	KeyFieldID                   = "id"
	KeyFieldURL                  = "url"
	KeyFieldEpisodeID            = "episodeId"
	KeyFieldName                 = "name"
	KeyFieldTitle                = "title"
	KeyFieldDesignation          = "designation"
	KeyFieldClassification       = "classification"
	KeyFieldAverageHeight        = "averageHeight"
	KeyFieldAverageLifespan      = "averageLifespan"
	KeyFieldLanguage             = "language"
	KeyFieldHeight               = "height"
	KeyFieldMass                 = "mass"
	KeyFieldModel                = "model"
	KeyFieldManufacture          = "manufacture"
	KeyFieldCostInCredit         = "costInCredit"
	KeyFieldLength               = "length"
	KeyFieldMaxAtmospheringSpeed = "maxAtmospheringSpeed"
	KeyFieldCrew                 = "crew"
	KeyFieldPassenger            = "passenger"
	KeyFieldCargoCapacity        = "cargoCapacity"
	KeyFieldConsumables          = "consumables"
	KeyFieldVehicleClass         = "vehicleClass"
	KeyFieldStarshipClass        = "starshipClass"
	KeyFieldHairColor            = "hairColor"
	KeyFieldHairColors           = "hairColors"
	KeyFieldSkinColor            = "skinColor"
	KeyFieldSkinColors           = "skinColors"
	KeyFieldEyeColor             = "eyeColor"
	KeyFieldEyeColors            = "eyeColors"
	KeyFieldBirthYear            = "birthYear"
	KeyFieldGender               = "gender"
	KeyFieldOpenCrawl            = "openCrawl"
	KeyFieldDirector             = "director"
	KeyFieldProducer             = "producer"
	KeyFieldHyperdriveRating     = "hyperdriveRating"
	KeyFieldMGLT                 = "mglt"
	KeyFieldRotationPeriod       = "rotationPeriod"
	KeyFieldOrbitalPeriod        = "orbitalPeriod"
	KeyFieldDiameter             = "diameter"
	KeyFieldClimate              = "climate"
	KeyFieldGravity              = "gravity"
	KeyFieldTerrain              = "terrain"
	KeyFieldSurfaceWater         = "surfaceWater"
	KeyFieldPopulation           = "population"
	KeyFieldReleaseDate          = "releaseDate"
	KeyFieldCreatedAt            = "createdAt"
	KeyFieldUpdatedAt            = "updatedAt"
	KeyFieldHomeworld            = "homeworld"
	KeyFieldFilms                = "films"
	KeyFieldVehicles             = "vehicles"
	KeyFieldStarships            = "starships"
	KeyFieldSpecies              = "species"
	KeyFieldSpecie              = "specie"
	KeyFieldImage                = "image"
	KeyFieldPage                 = "page"
	KeyFieldSearch               = "search"
	KeyFieldNext                 = "next"
	KeyFieldPrevious             = "previous"
	KeyFieldResults              = "results"
)

const (
	KeyHomeworld = "KeyHomeworld"
	KeyVehicle   = "KeyVehicle"
	KeyFilm      = "KeyFilm"
	KeyPeople    = "KeyPeople"
	KeyPeoples   = "KeyPeoples"
	KeyStarship  = "KeyStarship"
	KeySpecie    = "KeySpecie"
)
